In [15]:
import numpy as np
import pandas as pd
import pickle
import re
import spacy
from spacy.lang.en.stop_words import STOP_WORDS
import unicodedata
from sentence_transformers import models, SentenceTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from xgboost import XGBClassifier

In [2]:
nlp = spacy.load("en_core_web_sm", disable=["ents", "ner", "parser", "pos_"])

## 1. Data Acquisition

**Data Citation:**
```
@article{asai2023selfrag,
  author    = {Asai, Akari and Wu, Zeqiu and Wang, Yizhong and Sil, Avirup and Hajishirzi, Hannaneh},
  title     = {{Self-RAG}: Learning to Retrieve, Generate, and Critique through Self-Reflection},
  year      = {2023},
  journal   = { arXiv preprint arXiv:2310.11511 },
  URL       = {https://arxiv.org/abs/2310.11511}
}
```

In [ ]:
# Load data
raw_df = pd.read_json("hf://datasets/selfrag/selfrag_train_data/train.jsonl", lines=True)
raw_df.head()

,instruction,output,input,id,dataset_name
0,"In this task, you are given a context paragrap...",[Retrieval]<paragraph>2017 Portland train atta...,,flan_v2_88425,flan_v2
1,"Question: Write a text based on ""rangers show ...",[No Retrieval]six opposition candidates in the...,,flan_v2_18667,flan_v2
2,You will be given a sentence. Check whether th...,[No Retrieval]1\n****\n[Utility:5],,flan_v2_87754,flan_v2
3,Q:Is there a negative or positive tone to this...,[No Retrieval]Negative[Utility:5],,flan_v2_47789,flan_v2
4,Question: Fertility Clinics Vary on Embryo Dis...,[No Retrieval]Answer: World[Utility:5],,flan_v2_10803,flan_v2

In [ ]:
def check_retrieval(output) -> str:
  """Function to denote if retrieval took place when generating an output"""
  if re.search(r"\[Retrieval\]", output):
    return "true"
  elif re.search(r"\[No Retrieval\]", output):
    return "false"
  else:
    # Some outputs are tagged with `[Continue to Use Evidence]` and `Dialog`.
    # We could flag these as false but we will ignore them instead.
    return "null"

In [ ]:
# Apply check retrieval function
raw_df["retrieval"] = raw_df["output"].apply(check_retrieval)

In [ ]:
# Check for balance
raw_df["retrieval"].value_counts()

retrieval
true     74219
false    70362
null      1038
Name: count, dtype: int64

In [ ]:
# Remove unwanted rows
raw_df.drop(raw_df.loc[raw_df["retrieval"] == "null"].index, inplace=True)
raw_df["retrieval"].value_counts()

retrieval
true     74219
false    70362
Name: count, dtype: int64

## 2. Text Cleaning and Preprocessing

In [ ]:
def clean_preprocess(texts):
    with nlp.select_pipes(enable=["tokenizer", "lemmatizer", "attribute_ruler", "tagger"]):
        for doc in nlp.pipe(texts, batch_size=1000, n_process=2):
            tokens = [
                token.lemma_.lower() for token in doc if
                token.is_ascii and
                not token.is_stop and
                not token.is_punct and
                not token.like_email and
                not token.is_space
                ]
            yield " ".join(tokens)

In [ ]:
raw_df["cleaned_instruction"] = list(clean_preprocess(raw_df["instruction"].values))
raw_df.head()

,instruction,output,input,id,dataset_name,retrieval,cleaned_instruction
0,"In this task, you are given a context paragrap...",[Retrieval]<paragraph>2017 Portland train atta...,,flan_v2_88425,flan_v2,true,task given context paragraph tweet question ta...
1,"Question: Write a text based on ""rangers show ...",[No Retrieval]six opposition candidates in the...,,flan_v2_18667,flan_v2,false,question write text based rangers iron tie ser...
2,You will be given a sentence. Check whether th...,[No Retrieval]1\n****\n[Utility:5],,flan_v2_87754,flan_v2,false,given sentence check sentence grammatically co...
3,Q:Is there a negative or positive tone to this...,[No Retrieval]Negative[Utility:5],,flan_v2_47789,flan_v2,false,q negative positive tone product review = = = ...
4,Question: Fertility Clinics Vary on Embryo Dis...,[No Retrieval]Answer: World[Utility:5],,flan_v2_10803,flan_v2,false,question fertility clinics vary embryo disposa...

In [ ]:
raw_df.to_csv("cleaned_df.csv", columns=["cleaned_instruction", "retrieval"], index=False)

## 3. Feature Engineering

In [3]:
clean_df = pd.read_csv("https://github.com/Nate-Cheney/CIS-405-RAG_Classifier/raw/refs/heads/main/data/cleaned_df.csv")
clean_df.head()

                                 cleaned_instruction  retrieval
0  task given context paragraph tweet question ta...       True
1  question write text based rangers iron tie ser...      False
2  given sentence check sentence grammatically co...      False
3  q negative positive tone product review = = = ...      False
4  question fertility clinics vary embryo disposa...      False

In [4]:
clean_df = clean_df.dropna(subset=["cleaned_instruction"])

In [5]:
transformer = models.Transformer("sentence-transformers/all-MiniLM-L12-v2")
pooling = models.Pooling(transformer.get_word_embedding_dimension(), pooling_mode="mean")
model = SentenceTransformer(modules=[transformer, pooling])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/352 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [6]:
sentences = (clean_df["cleaned_instruction"].tolist())
SBERT_vector = model.encode(sentences, show_progress_bar=True)

Batches:   0%|          | 0/4515 [00:00<?, ?it/s]

In [7]:
ner_list = []
for sentence in sentences:
    doc = nlp(str(sentence))
    counts = {"PERSON": 0, "ORG": 0, "GPE": 0, "DATE": 0}
    for ent in doc.ents:
        if ent.label_ in counts:
            counts[ent.label_] += 1
    ner_list.append(list(counts.values()))
ner_vector = np.array(ner_list)

In [8]:
embeddings = (np.concatenate((SBERT_vector, ner_vector), axis=1))
clean_df["embeddings"]  = embeddings.tolist()
clean_df.head()

,cleaned_instruction,retrieval,embeddings
0,task given context paragraph tweet question ta...,True,"[0.08893557637929916, 0.14358608424663544, 0.0..."
1,question write text based rangers iron tie ser...,False,"[0.09296393394470215, 0.04364733770489693, -0...."
2,given sentence check sentence grammatically co...,False,"[0.10677994042634964, 0.33720147609710693, 0.0..."
3,q negative positive tone product review = = = ...,False,"[-0.09037359803915024, 0.015777895227074623, -..."
4,question fertility clinics vary embryo disposa...,False,"[0.07055126130580902, 0.28588759899139404, 0.0..."

# 4. Model training

In [9]:
X_vect = clean_df["embeddings"]
Y_data = clean_df["retrieval"]

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X_vect, Y_data, test_size=0.2, random_state=4, stratify=Y_data)

In [11]:
Model = LogisticRegression(max_iter=100)

In [12]:
Model.fit(np.array(X_train.tolist()), Y_train)

LogisticRegression()

In [13]:
Y_pred = Model.predict(np.array(X_test.tolist()))

In [14]:
print(accuracy_score(Y_test, Y_pred),"\n", confusion_matrix(Y_test, Y_pred))

0.7876522702104097
 [[11074  2983]
 [ 3153 11686]]

In [16]:
with open("RAG-Log-Reg.pkl", "wb") as f:
  pickle.dump(Model, f)

In [17]:
xgb_model = XGBClassifier(
    objective="binary:logistic",
    learning_rate=0.05,
    n_estimators=1000,
    max_depth=6,
    subsample=0.5,
    colsample_bytree=0.5,
    random_state=42
)

In [18]:
xgb_model.fit(np.array(X_train.tolist()), Y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.5, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=1000,
              n_jobs=None, num_parallel_tree=None, ...)

In [19]:
xgb_pred = xgb_model.predict(np.array(X_test.tolist()))

In [20]:
print(accuracy_score(Y_test, xgb_pred),"\n", confusion_matrix(Y_test, xgb_pred))

0.8266196013289037
 [[11666  2391]
 [ 2619 12220]]

In [21]:
with open("RAG-XGB.pkl", "wb") as f:
  pickle.dump(xgb_model, f)